version: '2'
services:
  discovery:
    image: ${DOCKER_USER}/discovery-service:${TAG}
    restart: always
    ports:
      - "8761:8761"
  gateway:
    image: ${DOCKER_USER}/api-gateway:${TAG}
    restart: always
    ports:
      - "8081:8081"
    links:
      - discovery
      - login
  login:
    image: ${DOCKER_USER}/login-microservice:${TAG}
    restart: always
    ports:
      - "9005:9005"
    links:
      - discovery