version: '2'
services:
  discovery:
    image: ${DOCKER_USER}/discovery-service:${TAG}
    restart: always
    ports:
      - "8761:8761"
  gateway:
    image: ${DOCKER_USER}/api-gateway:${TAG}
    restart: always
    ports:
      - "8081:8081"
    links:
      - discovery
      - login
  login:
    image: ${DOCKER_USER}/login-microservice:${TAG}
    restart: always
    ports:
      - "9005:9005"
    links:
      - discovery
# (mavogel): disabled cuz not tested in docker yet, but need to merge due to api update
#  account:
#    image: ${DOCKER_USER}/account-service:${TAG}
#    restart: always
#    ports:
#      - "6000:6000"
#    links:
#      - discovery
