version: '2'
services:
  api-gateway:
    image: ${GROUP}/api-gateway
    restart: always
    environment:
      SERVER_URL: ${SERVER_URL}
    ports:
      - "8081:8081"

  discovery-service:
    image: ${GROUP}/discovery-service
    restart: always
    ports:
      - "8761:8761"

  login-microservice:
    image: ${GROUP}/login-microservice
    restart: always
    environment:
      SERVER_URL: ${SERVER_URL}
    ports:
      - "9005:9005"
