server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
zuul:
    ignoredServices: '*'
    routes:
      login-api:
          path: /login-api/**
          serviceId: login
          stripPrefix: false
          url: http://login:9005/
ribbon:
  eureka:
    enabled: true