server:
  port: 8081
zuul:
    ignoredServices: '*'
    routes:
      login-api:
          path: /login-api/**
          serviceId: login
          stripPrefix: false
          url: http://login:9005/
eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/