server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVER_URL}:8761/eureka/
  instance:
    ip-address: ${SERVER_URL}
    preferIpAddress: true
    instanceId: "login-microservice"

spring:
  application:
    name: login-microservice