spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mefiroofficial/ui-lab/tree/master/configuration
        health:
          repositories:
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: config
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/